version: "3"

services:
  ui:
    image: glamhack/drenowatz
    build:
      context: .
      dockerfile: ui/docker/Dockerfile
    ports:
      - 3000:80

  stamps:
    build:
      context: stamps
    volumes:
      - ./stamps/main.py:/app/main.py
      - ./data:/app/data
